spring:
  cloud:
    aws:
      s3:
        bucket: mock-bucket
      region:
        static: ap-northeast-2
      credentials:
        access-key: mock-key
        secret-key: mock-secret
jwt:
  secret: mock-jwt-secret-key-must-be-very-long-and-secure-enough-32chars