spring:
  cloud:
    aws:
      s3:
        bucket: mock-bucket
      region:
        static: ap-northeast-2
      credentials:
        access-key: mock-key
        secret-key: mock-secret
  data:
    redis:
      host: localhost
      port: 6379

# JWT 시크릿 키를 Base64 형식의 안전한 값으로 설정 (중요!) 가짜값입니다.
jwt:
  secret: dGhpcy1pcy1hLXNhbXBsZS1zZWNyZXQta2V5LWZvci10ZXN0aW5nLXB1cnBvc2VzLWJhc2U2NA==