spring:
  config:
    import: "aws-parameterstore:/config/demo/"
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://${RDS_HOST}:3306/infinite?useSSL=false&serverTimezone=Asia/Seoul
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate # 운영은 스키마 보호를 위해 validate가 필수!
  cloud:
    aws:
      s3:
        bucket: ${S3_BUCKET_NAME}
jwt:
  secret:
    key: ${JWT_SECRET_KEY}
