spring:
  application:
    name: demo
  config:
    import: "optional:classpath:application-local.yml" # 로컬 설정 있으면 가져오기
  servlet:
    multipart:
      max-file-size: 10MB
  cloud:
    aws:
      region:
        static: ap-northeast-2
        #CDN cloudfront 주소
      cloudfront:
        domain: https://dvkdjefrta6hq.cloudfront.net

# 비즈니스 로직 및 공통 상수
jelly:
  price-per-unit: 300
  fan-membership-cost: 9
  dm-subscription-cost: 15

# Actuator 등 공통 설정
management:
  endpoints:
    web:
      exposure:
        include: health, prometheus, info
